apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lanenet-data
  namespace: ucm-vista
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 100Gi
≠